name: Orchard Rooms
favicon: null
layout_spectrum: 0.09457347146235406
typography_spectrum: 0.0911409396212548
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.44123928830958903
  lightness: 0.7747521894052625
  saturation: 0.1253056125715375
  rhythmicContrast: 0.9175010016188025
purpose: []
